### ISSUE TITLE
Fwd: "Who controls #metadata re https://faircookbook.elixir-europe.org/content/recipes/findability/registeringDatasets? "

### ISSUE THREAD

**Issue by egonw** [FAIRplus/the-fair-cookbook#419] opened 2022-03-31 06:20 UTC
[Question on Twitter](https://twitter.com/kidehen/status/1509134366118752259) about the ownership/authorship/controllership of the metadata embedded in recipes. I also note in the below image from the tweet that copyright/license information is missing from the machine readable info in the recipe:

![image](https://user-images.githubusercontent.com/26721/160989205-94a3f8e4-5bbb-4bcf-be40-b1b25050e413.png)

**Comment by proccaserra** [comment] 2022-03-31 06:42
duplicate of #418

**Closed by proccaserra** 2022-03-31 06:42 UTC

**Comment by egonw** [comment] 2022-03-31 06:44
@proccaserra, sorry! I had not seen that (obviously)

**Comment by proccaserra** [comment] 2022-03-31 07:30
No pb at all. The license information is actually available. I think the screenshot from the tweet is from earlier version as one can also see the FCBxxx identifier. the "production" recipe has FCB013 identifier.
As for owner, authors, indeed, these could/should be added since we have had orcids and casrai credit tags.
